end_point = 'http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcSHTrade?_wadl&type=xml'
encoding_key = 'ebl8Ut%2FJ2dsO84047u5ZUjBH53zpBM3YTtMLdGH0FkE6Ukn1z8Hy9WN45TvTQ%2BbdBRQctFDMT7GBZHqttCA8yg%3D%3D'

In [7]:
end_point = 'http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcSHTrade?_wadl&type=xml'
encoding_key = 'ebl8Ut%2FJ2dsO84047u5ZUjBH53zpBM3YTtMLdGH0FkE6Ukn1z8Hy9WN45TvTQ%2BbdBRQctFDMT7GBZHqttCA8yg%3D%3D'
decoding_key = 'ebl8Ut/J2dsO84047u5ZUjBH53zpBM3YTtMLdGH0FkE6Ukn1z8Hy9WN45TvTQ+bdBRQctFDMT7GBZHqttCA8yg=='

In [8]:
'http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcSHTradeex_url =f?LAWD_CD=11110&DEAL_YMD=201512&serviceKey={encoding_key}'

In [39]:
import requests
import xmltodict
import json
import pandas as pd

resp_xml = requests.get(ex_url)
resp_dict = xmltodict.parse(resp_xml.text)
dict = json.loads(json.dumps(resp_dict))
item_dict  = dict.get('response', {}).get('body', {}).get('items')
pd.DataFrame(item_dict['item'])

,거래금액,거래유형,건축년도,년,대지면적,매도자,매수자,법정동,연면적,월,일,주택유형,중개사소재지,지번,지역코드,해제사유발생일,해제여부
0,"86,000",None,1955,2015,66.1,None,None,누하동,39.67,12,28,단독,None,1**,11110,None,None
1,"38,500",None,1985,2015,62.8,None,None,옥인동,37.26,12,17,단독,None,4*,11110,None,None
2,"118,000",None,1991,2015,92.6,None,None,체부동,206.01,12,31,단독,None,1**,11110,None,None
3,"81,000",None,1900,2015,145.5,None,None,필운동,79.34,12,4,단독,None,1**,11110,None,None
4,"210,000",None,1997,2015,88.2,None,None,필운동,297.16,12,23,단독,None,1**,11110,None,None
5,"220,000",None,1994,2015,202.6,None,None,운니동,411.81,12,9,다가구,None,4*,11110,None,None
6,"59,900",None,1900,2015,62.8,None,None,익선동,30.68,12,16,단독,None,1**,11110,None,None
7,"110,000",None,1900,2015,72.7,None,None,팔판동,79.57,12,1,단독,None,9*,11110,None,None
8,"98,300",None,1970,2015,73.7,None,None,삼청동,124.89,12,30,단독,None,1*,11110,None,None
9,"63,000",None,1900,2015,69.4,None,None,묘동,34.05,12,1,단독,None,*,11110,None,None
10,"90,000",None,1987,2015,163,None,None,이화동,247.75,12,8,단독,None,*,11110,None,None
11,"42,000",None,1994,2015,105.3,None,None,연건동,238.46,12,2,다가구,None,3**,11110,None,None
12,"34,000",None,1978,2015,98.2,None,None,충신동,57.75,12,4,단독,None,*,11110,None,None
13,"11,500",None,1978,2015,27.4,None,None,충신동,38.34,12,11,단독,None,*,11110,None,None
14,"215,000",None,1996,2015,298.3,None,None,동숭동,647.33,12,28,다가구,None,2*,11110,None,None
15,"71,500",None,1994,2015,128.9,None,None,명륜1가,179.55,12,22,다가구,None,1*,11110,None,None
16,"44,000",None,1992,2015,92.6,None,None,명륜2가,66.12,12,30,단독,None,1**,11110,None,None
17,"60,000",None,1973,2015,97.5,None,None,명륜3가,126.23,12,18,다가구,None,5*,11110,None,None
18,"66,500",None,1996,2015,109.8,None,None,명륜3가,176.85,12,30,다가구,None,1**,11110,None,None
19,"37,500",None,NaN,2015,128.9,None,None,창신동,170.89,12,1,다가구,None,2*,11110,None,None
20,"62,000",None,1976,2015,119.9,None,None,창신동,149.55,12,7,단독,None,2*,11110,None,None
21,"40,000",None,1990,2015,65.1,None,None,창신동,109.13,12,9,다가구,None,5**,11110,None,None
22,"24,000",None,1972,2015,46.3,None,None,창신동,75.22,12,10,다가구,None,6**,11110,None,None
23,"37,000",None,1986,2015,129.7,None,None,창신동,215.05,12,21,단독,None,2*,11110,None,None
24,"126,000",None,1986,2015,188.5,None,None,창신동,359.85,12,26,단독,None,1**,11110,None,None
25,"58,000",None,1983,2015,165.3,None,None,창신동,215.88,12,28,단독,None,2*,11110,None,None
26,"34,000",None,1975,2015,112.4,None,None,창신동,36.5,12,29,단독,None,2*,11110,None,None
27,"37,000",None,1900,2015,85.3,None,None,숭인동,49.59,12,18,단독,None,1**,11110,None,None
28,"8,000",None,1985,2015,32.4,None,None,숭인동,16.41,12,24,단독,None,5*,11110,None,None
29,"170,264",None,1900,2015,222,None,None,숭인동,128.93,12,28,단독,None,2**,11110,None,None
30,"43,071",None,1959,2015,93.5,None,None,숭인동,110.55,12,28,단독,None,2**,11110,None,None
31,"32,000",None,NaN,2015,102.43,None,None,구기동,56.86,12,9,단독,None,2**,11110,None,None
32,"47,000",None,1974,2015,99,None,None,평창동,77.52,12,5,단독,None,5**,11110,None,None
33,"189,000",None,1993,2015,475,None,None,평창동,307.29,12,7,단독,None,3**,11110,None,None
34,"245,000",None,2001,2015,558,None,None,평창동,345.35,12,13,단독,None,4**,11110,None,None
35,"180,000",None,1978,2015,615,None,None,평창동,229.93,12,21,단독,None,5**,11110,None,None
36,"120,000",None,1979,2015,491,None,None,평창동,227.43,12,28,단독,None,4**,11110,None,None
37,"245,000",None,2001,2015,558,None,None,평창동,345.35,12,31,단독,None,4**,11110,None,None
38,"495,000",None,1971,2015,1276,None,None,부암동,266.71,12,9,단독,None,2**,11110,None,None
39,"140,000",None,1974,2015,334,None,None,홍지동,208.5,12,1,단독,None,3*,11110,None,None
40,"75,000",None,1900,2015,284,None,None,신영동,39.13,12,1,단독,None,8*,11110,None,None
41,"50,000",None,1963,2015,162,None,None,신영동,49.62,12,1,단독,None,8*,11110,None,None
42,"15,000",None,1900,2015,46,None,None,신영동,17.68,12,1,단독,None,1**,11110,None,None
43,"38,000",None,1970,2015,139,None,None,신영동,122.61,12,31,단독,None,2**,11110,None,None